version: '3.8'

services:
  bot:
    build: .
    volumes:
      - ./data/pdfs:/app/data/pdfs
      - ./src:/app/src
      - ./.env:/app/.env
    restart: unless-stopped
    environment:
      - PYTHONUNBUFFERED=1